export const todoActions = {
  FETCH_TODOS: "FETCH_TODOS",
  REQUEST_TODOS: "REQUEST_TODOS",
  RECEIVE_TODOS: "RECEIVE_TODOS",
  RECEIVE_TODOS_ERROR: "RECEIVE_TODOS_ERROR",
  TOGGLE_TODO: "TOGGLE_TODO",
  POST_TODO: "POST_TODO",
  REQUEST_CREATE_TODO: "REQUEST_CREATE_TODO",
  RECEIVE_CREATED_TODO: "RECEIVE_CREATED_TODO",
  RECEIVE_CREATED_TODO_ERROR: "RECEIVE_CREATED_TODO_ERROR",
};

export const userActions = {
  POST_USER: "POST_USER",
  REQUEST_CREATE_USER: "REQUEST_CREATE_USER",
  RECEIVE_CREATED_USER: "RECEIVE_CREATED_USER",
  RECEIVE_CREATED_USER_ERROR: "RECEIVE_CREATED_USER_ERROR",
  LOGIN_USER: "LOGIN_USER",
  REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
  RECEIVE_LOGGED_IN_USER: "RECEIVE_LOGGED_IN_USER",
  RECEIVE_LOGGED_IN_USER_ERROR: "RECEIVE_LOGGED_IN_USER_ERROR",
};

export const filterActions = {
  SELECT_FILTER: "SELECT_FILTER",
};
